### ISSUE TITLE
Using DEqMS for Phosphoproteomics Data

### ISSUE THREAD

**Issue by jesswhitts** [yafeng/DEqMS#20]
Hello, 

I was wondering about the suitability of DEqMS for analysing phosphoproteomics data? Where I essentially have a set of phosphosites with quantification values, is this tool suitable for this application?

Best,
jess

**Comment by yafeng** [comment]
@jesswhitts Hi，
Yes, DEqMS can be used for phosphoproteomics. If your aim is to detected differential phosphorites, you should combine peptides/PSMs supporting the same phosphosites, the input matrix is phosphosite quant matrix  and use the number of peptides/PSMs per phosphosite for the fit3$count variable.

Yafeng

**Comment by jesswhitts** [comment]
Awesome, thanks for your help!
